### ISSUE TITLE
Compile error  

### ISSUE THREAD

**Issue by ZQ32** [atenpas/gpd2#10]
after i    
 cmake .. -DUSE_CAFFE=ON
              cmake .. -DBUILD_DATA_GENERATION=ON　
there is no problem,
 but after i  make -j  The following error occurred   Can you give me some advice?
 

![Screenshot from 2019-08-29 16-32-57](https://user-images.githubusercontent.com/46440854/63924369-ba2f6580-ca7a-11e9-8480-51f0d330b99d.png)

**Comment by atenpas** [comment]
Could you show the output of `cmake`?

**Comment by ZQ32** [comment]
> Could you show the output of `cmake`?

**Comment by ZQ32** [comment]
> Could you show the output of `cmake`?

![lpf@lpf-legion-y7000-2019: ~-Downloads-gpd2-master-build_008](https://user-images.githubusercontent.com/46440854/63988368-81d96700-cb0e-11e9-9a98-0cc24ac30776.png)
![lpf@lpf-legion-y7000-2019: ~-Downloads-gpd2-master-build_009](https://user-images.githubusercontent.com/46440854/63988369-843bc100-cb0e-11e9-8842-db6fd96831f5.png)

**Comment by atenpas** [comment]
Could you delete the build folder and recompile it?

**Comment by ZQ32** [comment]
I created these three folders according to  **generate_data.cfg**,　　
data_root = /home/xxx/data1/gpd/bigbird_pcds/objects_file_location，
objects_file_location = /home/xxx/data1/gpd/bigbird_pcds/　
output_root = /home/xxx/data1/gpd/models/test/　then how to arrange these three folders, what files should be included in the folder, can you give some detailed information?
After I run **./generate_data ../cfg/generate_data.cfg**, output the following.I need to download BigBIRD: (Big) Berkeley Instance Recognition Dataset?
![Screenshot from 2019-09-03 17-16-14](https://user-images.githubusercontent.com/46440854/64161065-92237600-ce6f-11e9-8aa2-f53e9d2036ab.png)

**Comment by atenpas** [comment]
Is this related to your original issue? If not, would you mind opening a new issue?

**Comment by ZQ32** [comment]
ok
