### ISSUE TITLE
can i use caffe

### ISSUE THREAD

**Issue by lpf0** [atenpas/gpd2#7]
how can i use caffe in this project

**Comment by atenpas** [comment]
This is explained in the [README](https://github.com/atenpas/gpd2#cnn_frameworks).

**Comment by lpf0** [comment]
thanks verymuch !!!,can you give me some more details?

**Comment by lpf0** [comment]
thanks verymuch !!!,can you give me some more details about how to use caffe in this gpd2?
my email    lpfdzq@gmail.com

**Comment by atenpas** [comment]
In the directory *gpd2/build*, you should run `ccmake ..`. In the GUI that's shown next, set `USE_CAFFE` to `ON` (and every other `USE_*` to `OFF`), and [c]onfigure and [g]enerate. Then you can run the usual `make`.

**Comment by lpf0** [comment]
Thank you very much. Have a good life.
