### ISSUE TITLE
Inference engine exception

### ISSUE THREAD

**Issue by cyu-craftnetics** [atenpas/gpd2#8]
Hi, 
I'm trying to run the example with OpenVino but I've been getting an inference engine exception. I'm not sure what I'm missing. Here's the response when I run './detect_grasps ../cfg/eigen_params.cfg ../tutorials/krylon.pcd'

![image](https://user-images.githubusercontent.com/50259886/63404730-38b04700-c399-11e9-9158-f54e41d35f93.png)

Thanks!
Calvin

**Comment by atenpas** [comment]
You're running it with the wrong config file. You can use `cfg/vino_params_12channels.cfg`.

**Comment by cyu-craftnetics** [comment]
thanks! Yes, I was able to figure that out and got it working.
